### ISSUE TITLE
0.0.5-SNAPHOT in pom.xml

### ISSUE THREAD

**Issue by StephanPraetsch** [KnisterPeter/jreact-examples#2]
Hi,

your dependency does not exist: https://github.com/KnisterPeter/jreact-examples/blob/master/simple-spring-boot/pom.xml#L41

It should be 0.0.4 I suppose (this is currently the newest version on https://mvnrepository.com/artifact/de.matrixweb/jreact)

Best regards

**Comment by KnisterPeter** [comment]
Would you mind to create a PR? 😃
