### ISSUE TITLE
changes does not appear

### ISSUE THREAD

**Issue by keremozkanvivense** [KnisterPeter/jreact-examples#3]
i tried this project (0.0.4 version), it works but when i made changes in app.js file
(changed text    'Hello, '    to    'Hellox, '     ), it does not appear in browser. 
i did maven clean install, restart application but i does not show.

**Comment by KnisterPeter** [comment]
@keremozkanvivense This repository is only for demo and should not be used as is. It contains a lot outdated dependencies.
